# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171026_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[users.validators.validate_phone]),
        ),
    ]
