# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171026_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClerkProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[users.validators.validate_phone])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clerk_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
