# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='ip',
            field=models.GenericIPAddressField(),
            preserve_default=False,
        ),
    ]
