# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 08:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20171026_1450'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='File number/Customer Reference (Optional)')),
                ('case', models.CharField(max_length=150, verbose_name='Case #')),
                ('party_name', models.CharField(max_length=100, verbose_name='Party or Entity name')),
                ('name', models.CharField(max_length=100, verbose_name='Exact name')),
                ('needed_date', models.DateField(verbose_name='Date you need')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CustomerProfile')),
            ],
        ),
    ]
